import Providers from "../../../providers";
// let name = "";
export default function RootLayout({ children, params }) {
  // name = params.prid;
  // console.log("prid is");
  // console.log(name);

  return <Providers>{children}</Providers>;
}
export const metadata = {
  title: "P",
  description: "Generated by create next app",
};
