import Providers from "../../../providers";


export default function RootLayout({ children}) {
  return (
    <Providers>
      {children}
    </Providers>
  );
}
export const metadata = {
  title: "C",
  description: "Generated by create next app",
};